version: '3.8'
services:
  moviesDB:
    container_name: moviesDB
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=moviedb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test1
      - MYSQL_PASSWORD=password1
    ports:
      - 3306:3306
volumes:
  mysql-data: